### ISSUE TITLE
deleting queue and the songs after disconnecting the bot

### ISSUE THREAD

**Issue by AliDayyani** [SudhanPlayz/Discord-MusicBot#947] opened 2022-06-26 10:38 UTC
when I disconnect bot the song steel playing can you add something when i disconnected the bot the queue delete too

**Comment by TwixGamer00** [comment] 2022-06-26 11:22
Wait, im sorry but can you explain what you mean? I don't really get it tbh

**Comment by AliDayyani** [comment] 2022-06-26 11:27
when i disconnect the bot without dc commend it steel playing the queue but its not in the voice if you didnt get it get me you email i send a video to you

**Comment by TwixGamer00** [comment] 2022-06-26 11:39
How is it playing if its not in a vc?

**Comment by BioCla** [comment] 2022-06-26 12:11
I wasn't able to reproduce the issue. Furthermore, the code already implements the thing you're asking for

```js
     .on("playerMove", (player, oldChannel, newChannel) => {
        const guild = client.guilds.cache.get(player.guild);
        if (!guild) return;
        const channel = guild.channels.cache.get(player.textChannel);
        if (oldChannel === newChannel) return;
        if (newChannel === null || !newChannel) {
          if (!player) return;
          if (channel)
            channel.send({
              embeds: [
                new MessageEmbed()
                  .setColor(client.config.embedColor)
                  .setDescription(`Disconnected from <#${oldChannel}>`),
              ],
            });
          return player.destroy(); // Right here <---------
        } else {
          player.voiceChannel = newChannel;
          setTimeout(() => player.pause(false), 1000);
          return undefined;
        }
      })
  ```

**Comment by DevAmiyo** [comment] 2022-06-26 13:20
> when i disconnect the bot without dc commend it steel playing the queue but its not in the voice if you didnt get it get me you email i send a video to you

Can you upload the video in some online video hosting site like [Streamable](https://streamable.com) and share the link here so we have a better understanding of what exactly the issue is?

**Comment by AliDayyani** [comment] 2022-06-26 14:48
here is a video from that problem https://streamable.com/8vtkrc

**Comment by AliDayyani** [comment] 2022-06-26 14:48
here is a video from that problem https://streamable.com/8vtkrc

**Comment by DarrenOfficial** [comment] 2022-06-26 15:15
is this v4 or v5?

**Comment by Saud-97** [comment] 2022-06-26 15:59
Doesn't look like v5 or it was heavily modified. ¯\_(ツ)_/¯

**Comment by AliDayyani** [comment] 2022-06-26 16:09
> is this v4 or v5?

what do you mean

**Comment by Saud-97** [comment] 2022-06-26 16:12
> > is this v4 or v5?
> 
> what do you mean

Come to the discord and ask your questions there. It seems you are confused a bit.

**Comment by DevAmiyo** [comment] 2022-06-27 18:32
I think I know what he means.

@AliDayyani [`v4`](https://github.com/SudhanPlayz/Discord-MusicBot/tree/master) kind of has this issue where it ignores manual bot move/disconnect events.
This is fixed in [`v5`](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5). If you want to fix your issue use the [`v5`](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5) branch.

> Follow [these steps](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5#--important-note-if-youre-switching-from-v4-to-v5) to switch to [v5](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5).

**Comment by Saud-97** [comment] 2022-07-01 18:29
This should be closed as not planned since it's already fixed in v5

**Comment by DevAmiyo** [comment] 2022-07-07 10:11
@AliDayyani / @DarrenOfficial Can you close this issue please, since its already fixed?

**Closed** 2022-07-07 10:19 UTC
Labels: type: enhancement
