### ISSUE TITLE
Queue randomly ends, bot isn't recognizing manual disconnection from the voice channel

### ISSUE THREAD

**Issue by Botond0207** [SudhanPlayz/Discord-MusicBot#1192] opened 2023-03-07 14:51 UTC
**Please describe the problem you are having in as much detail as possible: Queue randomly ends after first song has been played while or after using loop. The user has to use the play command again to make the song play. The bot doesn't recognize being manually disconnected from the voice channel which results in a bug where if you type the play command the bot starts playing but it 's not connected to any voice channel.  **

![image](https://user-images.githubusercontent.com/84857758/223455878-2759c6c1-2855-4827-9a74-175bc0adc5f2.png)
![image](https://user-images.githubusercontent.com/84857758/223456491-94199244-de68-44b1-8dab-0c76528bc8c6.png)

### Essentials:

- Bot Version: v4.1.4
- Commit Hash: -
- Node.js version: v18.12.0
- Operating system: Linux (I belive)

#### Additional system info
- Is it virtualized? (Docker or ...) : It's hosted on daki.cc
- What CPU is it running on (X86 or ARM or...): -
- Additional details that might help us figure out the problem:

### Relevant client options:

- partials: none
- gateway intents: none
- other: none

**Comment by Assassin654** [comment] 2023-03-07 16:54
Use v5

**Comment by frorayz** [comment] 2023-03-09 04:30
> Use v5

Same problem on v5

**Comment by LewdHuTao** [comment] 2023-03-09 06:13
> Same problem on v5, can confirm (for queue randomly ending)

change your lavalink

**Comment by frorayz** [comment] 2023-03-09 13:48
> > Same problem on v5, can confirm (for queue randomly ending)
> 
> change your lavalink

I self host mine. Not sure whats the problem.

**Comment by LewdHuTao** [comment] 2023-03-09 14:35
> I self host mine. Not sure whats the problem.

where did you host your lavalink? try change your lavalink first and see if there is any changes, you can get lavalink list here: https://lavalink-list.darrennathanael.com/NoSSL/lavalink-without-ssl/

**Comment by CalendulaED** [comment] 2023-03-09 16:30
I have the same problem, did you solve it?

**Comment by Botond0207** [comment] 2023-03-09 16:36
> 

Sadly no. Since i don't know js i don't have any other options than waiting. In my exprience it's not a lavalink related issue, i tried 4 different lavalinks and the problem still occurs in different forms.

**Comment by Assassin654** [comment] 2023-03-09 17:28
V5 does not need a Spotify id. If you have a reliable lavalink and your bot has a stable connection, there should be no issue

**Comment by LewdHuTao** [comment] 2023-03-09 18:53
> I also try to use a different lava link, and it doesn't work. It usually plays 10-20 songs, and it just stoped, or maybe just not making sounds. I am trying test if v5 works or not, but the config file didn't have a place for me to enter the Spotify Client ID place.

it's probably lavalink issue, the lavalink you used maybe accidentally crashed and restarted causing the queue to end itself or make no sound in vc, anyway if you're currently using lavalink with ssl try switching it to lavalink non-ssl
cause most of lavalink with ssl is hosted in replit.

**Comment by LewdHuTao** [comment] 2023-03-09 18:59
> Sadly no. Since i don't know js i don't have any other options than waiting. In my exprience it's not a lavalink related issue, i tried 4 different lavalinks and the problem still occurs in different types.

like @Assassin654 said as long you have reliable host and lavalink the queue shouldn't end itself, so try switch to non-ssl lavalink if you're using ssl lavalink and if the queue still end itself i recommend you to get a vps/rpd to host your own lavalink.

**Comment by CalendulaED** [comment] 2023-03-10 00:07
> > I also try to use a different lava link, and it doesn't work. It usually plays 10-20 songs, and it just stoped, or maybe just not making sounds. I am trying test if v5 works or not, but the config file didn't have a place for me to enter the Spotify Client ID place.
> 
> it's probably lavalink issue, the lavalink you used maybe accidentally crashed and restarted causing the queue to end itself or make no sound in vc, anyway if you're currently using lavalink with ssl try switching it to lavalink non-ssl cause most of lavalink with ssl is hosted in replit.

I think I use the uptimerobot to make the lavalink on replit work, if the problem is replit, will hosting it on separate server make it better? Because I am not sure whether non-ssl lavalink safe or not.

**Comment by CalendulaED** [comment] 2023-03-10 00:28
I also test the v5, and no matter what lava link I choose, SSL, or non-ssl, it always jumps back and force to disconnect and reconnect, and stops after several try. Always repeating those:
```
[10:2:2023 - 0:27] | Node: Main Node | Lavalink node is disconnected.
[10:2:2023 - 0:27] | Node: Main Node | Lavalink node is reconnecting.
```

**Comment by LewdHuTao** [comment] 2023-03-10 00:45
> I also test the v5, and no matter what lava link I choose, SSL, or non-ssl, it always jumps back and force to disconnect and reconnect, and stops after several try. Always repeating those:
> 
> ```
> 
> [10:2:2023 - 0:27] | Node: Main Node | Lavalink node is disconnected.
> 
> [10:2:2023 - 0:27] | Node: Main Node | Lavalink node is reconnecting.
> 
> ```

then you got the answer why the queue end itself,seems like you host your lavalink in replit and switch to several lavalink but the queue still end itself. if have a credit card you can try apply for oracle free tier vps and host your lavalink there

**Comment by LewdHuTao** [comment] 2023-03-10 00:50
> I think I use the uptimerobot to make the lavalink on replit work, if the problem is replit, will hosting it on separate server make it better? Because I am not sure whether non-ssl lavalink safe or not.

both ssl lavalink and non-ssl lavalink safe

**Comment by CalendulaED** [comment] 2023-03-10 00:50
> > I also test the v5, and no matter what lava link I choose, SSL, or non-ssl, it always jumps back and force to disconnect and reconnect, and stops after several try. Always repeating those:
> > ```
> > 
> > [10:2:2023 - 0:27] | Node: Main Node | Lavalink node is disconnected.
> > 
> > [10:2:2023 - 0:27] | Node: Main Node | Lavalink node is reconnecting.
> > ```
> 
> then you got the answer why the queue end itself,seems like you host your lavalink in replit and switch to several lavalink but the queue still end itself. if you have a credit card you can try apply for oracle free tier vps and host your lavalink there

I am actually using the oracle one to host the bot, but not yet know how to host the lavalink there.
For v4, no matter when will the bot stop, it can run at first. However, for the v5, I have test several of lavalink, the program didn't run after 200 of retry.

**Comment by LewdHuTao** [comment] 2023-03-10 01:01
> I am actually using the oracle one to host the bot, but not yet know how to host the lavalink there.
> 
> For v4, no matter when will the bot stop, it can run at first. However, for the v5, I have test several of lavalink, the program didn't run after 200 of retry. 
> 

here a docs on how to host lavalink: https://darrennathanael.com/post/how-to-lavalink/

**Comment by LewdHuTao** [comment] 2023-03-11 13:59
ill close this issue
- to fix bot isnt recognized manually disconnect from vc - switch to [v5](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5)
- to fix queue randomly end by itself - switch to better lavalink (recommend to host your own lavalink but not host it in replit)

feel free to reopen if the problem still exist when you already do 2 steps above

**Closed by LewdHuTao** 2023-03-11 13:59 UTC
Labels: type: bug

**Comment by frorayz** [comment] 2023-03-12 08:28
> > I self host mine. Not sure whats the problem.
> 
> where did you host your lavalink? try change your lavalink first and see if there is any changes, you can get lavalink list here: https://lavalink-list.darrennathanael.com/NoSSL/lavalink-without-ssl/

I host mine on my dedicated server. First of all it has this error on start:
`Lavalink node has an error: Unexpected op "ready" with data: [object Object].`

Then It just randomly starts pausing or stopping completely in the middle of playing. Also I have these errors, not sure if they are connected. Also also this started recently never happened before when I used v5.
```
2023-03-08 04:55:43.662  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":false}
2023-03-08 04:55:43.663  INFO 161546 --- [XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
2023-03-08 06:13:49.083 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:53092
2023-03-08 06:13:49.112 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:58270
2023-03-08 07:14:00.690  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
2023-03-08 15:53:41.404 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:46616
2023-03-08 15:53:41.659 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:37066
2023-03-08 23:15:12.157 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:59762
2023-03-08 23:15:12.389 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:34828
``` 
Please advise further.

**Comment by LewdHuTao** [comment] 2023-03-12 08:33
> I host mine on my dedicated server. First of all it has this error on start:
> 
> `Lavalink node has an error: Unexpected op "ready" with data: [object Object].`
> 
> 
> 
> Then It just randomly starts pausing or stopping completely in the middle of playing. Also I have these errors, not sure if they are connected. Also also this started recently never happened before when I used v5.
> 
> ```
> 
> 2023-03-08 04:55:43.662  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":false}
> 
> 2023-03-08 04:55:43.663  INFO 161546 --- [XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
> 
> 2023-03-08 06:13:49.083 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:53092
> 
> 2023-03-08 06:13:49.112 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:58270
> 
> 2023-03-08 07:14:00.690  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
> 
> 2023-03-08 15:53:41.404 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:46616
> 
> 2023-03-08 15:53:41.659 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:37066
> 
> 2023-03-08 23:15:12.157 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:59762
> 
> 2023-03-08 23:15:12.389 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:34828
> 
> ``` 
> 
> Please advise further.

i could see that the player randomly paused and i had no idea why that happened, as of now you can try reinstall your lavalink server, update your lavalink jar to 3.7.5 and use the latest application.yml

**Comment by LewdHuTao** [comment] 2023-03-12 08:34
forgot to ask, are you using custom lavalink jar or original lavalink jar from freya repo?

**Comment by frorayz** [comment] 2023-03-12 08:37
> forgot to ask, are you using custom lavalink jar or original lavalink jar from freya repo?

Original



> > I host mine on my dedicated server. First of all it has this error on start:
> > `Lavalink node has an error: Unexpected op "ready" with data: [object Object].`
> > Then It just randomly starts pausing or stopping completely in the middle of playing. Also I have these errors, not sure if they are connected. Also also this started recently never happened before when I used v5.
> > ```
> > 
> > 2023-03-08 04:55:43.662  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":false}
> > 
> > 2023-03-08 04:55:43.663  INFO 161546 --- [XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
> > 
> > 2023-03-08 06:13:49.083 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:53092
> > 
> > 2023-03-08 06:13:49.112 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:58270
> > 
> > 2023-03-08 07:14:00.690  INFO 161546 --- [XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"pause","guildId":"xxx","pause":true}
> > 
> > 2023-03-08 15:53:41.404 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:46616
> > 
> > 2023-03-08 15:53:41.659 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:37066
> > 
> > 2023-03-08 23:15:12.157 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:59762
> > 
> > 2023-03-08 23:15:12.389 ERROR 161546 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /ip:34828
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please advise further.
> 
> i could see that the player randomly paused and i had no idea why that happened, as of now you can try reinstall your lavalink server, update your lavalink jar to 3.7.5 and use the latest application.yml

I am using the latest afaik. its 3.7.5 and also using the latest application.yml
