### ISSUE TITLE
Heroku fail to deploy

### ISSUE THREAD

**Issue by doublep21** [SudhanPlayz/Discord-MusicBot#835] opened 2022-05-08 19:00 UTC
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by BioCla** [comment] 2022-05-08 19:01
Please use the correct template to report a bug and fill everything you can out with the most detail possible:

---
name: Bug report
about: Report incorrect or unexpected behavior of the Music Bot
title: ""
labels: "s: unverified, type: bug"
assignees: ""
---



**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
// Place your code here
```

**Further details:**

- discord.js version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Relevant client options:**

- partials: none
- gateway intents: none
- other: none

**Comment by doublep21** [comment] 2022-05-08 19:04
> Please use the correct template to report a bug and fill everything you can out with the most detail possible:
> 
> **Please describe the problem you are having in as much detail as possible:**
> 
> **Include a reproducible code sample here, if possible:**
> 
> ```js
> // Place your code here
> ```
> 
> **Further details:**
> 
> * discord.js version:
> * Node.js version:
> * Operating system:
> * Priority this issue should have – please be realistic and elaborate if possible:
> 
> **Relevant client options:**
> 
> * partials: none
> * gateway intents: none
> * other: none

i didn't use it because i just used the link for heroku

**Comment by BioCla** [comment] 2022-05-08 19:17
> i didn't use it because i just used the link for heroku

While I still think you should fill it out, The problem seems to be that someone has reported the repo on heroku and is being prevented from being forked.
The fix for this would be to (probably) rename the repo
at least according to this similar issue [here](https://github.com/developeranaz/Mega-index-heroku/issues/28)

**Comment by DarrenOfficial** [comment] 2022-05-12 00:47
Solved.

**Closed by DarrenOfficial** 2022-05-12 00:47 UTC
Labels: type: bug
