### ISSUE TITLE
command do not work properly.

### ISSUE THREAD

**Issue by TristannSadge** [SudhanPlayz/Discord-MusicBot#999] opened 2022-07-17 13:52 UTC
Hi, i have a small problem if i try command like /queue this happened.
the same thing happens if you use the /play command, But only when you add playlists
![image](https://user-images.githubusercontent.com/108361190/179401536-b7ba05ea-ac90-4f10-9f74-121bd419f4f0.png)
![image](https://user-images.githubusercontent.com/108361190/179401546-c82dd93e-7816-492a-be7e-2c8e6e6e7616.png)

I do not touch any file. Only config...
i dont know what am i doing wrong.

**Comment by JotaroKujo0525** [comment] 2022-07-18 04:07
kinda a duplicate of your issue #1000 , they have the same issue, so please continue on the issue there

**Closed by JotaroKujo0525** 2022-07-18 04:07 UTC
Labels: type: bug
